| **Kinga Węzka** <BR> kinga.wezka@pw.edu.pl  <BR> Warsaw University of Technology <BR> Faculty Geodesy and Cartography <BR> Plac Politechniki 1 (room 38)<BR> 00-661 Warszawa, POLAND<BR> <A href="https://www.google.com/maps/place/Gmach+G%C5%82%C3%B3wny+Politechniki+Warszawskiej/@52.220656,21.0094422,19z/data=!3m1!4b1!4m5!3m4!1s0x471ecce951c85a19:0x712b0e1503c42b91!8m2!3d52.220656!4d21.0099894"> N 52&ordm; 12' 45&quot; / E 21&ordm; 03' 51&quot;</A></B><BR> | <a rel="license" href="https://www.pw.edu.pl"><img alt="Politechnika Warszawska" style="border-width:0" src="https://www.pw.edu.pl/design/pw/images/znak-pw.png" /></a> |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    


# Spis tresci:

1. [Biblioteka NumPy](#wprowadzenie)
2. [Tablice ndarray](#sec2)
    1. [Tworzenie tablic](#sec2A)
    2. [Inspekcja tablic](#sec2B)
    3. [Typy danych w tablicy](#sec2C)
    4. [Odnoszenie się do elementów](#sec2D)
    5. [Fancy indexing - indeksowanie przy pomocy tablic indeksów](#sec2E)
3. [Kopia vs referencja](#sec3) 
4. [Działanie Numpy - Działanie Numpy - funkcje dla wszystkich elementów tablicy ](#sec4) 
5. [Broadcasting - operacje element po elemencie](#sec5) 
6. [Operacje logiczne dla tablic](#sec6)
7. [Dane NaN lub None](#sec7)
8. [Zapisywanie i wczytywanie tablic](#sec8)
9. [Zapisywanie i wczytywanie plików tekstowych](#sec9)
10. [Manipulacje tablicami](#sec10)
    1. [Zmiana kształtu macierzy  - wypłaszczenie](#sec10A)
    2. [Dodawanie i usuwanie elementów tablicy (append, insert, delete)](#sec10B)
    3. [Łączenie tablic (pionowo, poziomo)](#sec10C)

# 1. Biblioteka NumPy  - wprowadzenie<a name="wprowadzenie"></a>
Biblioteka NumPy (ang. Numeric Python) jest podstawową biblioteką do obliczeń naukowych w Pytonie. 
Zapewnia wysokowydajność poprzez zastosowanie obiektów w formie wielowymiarowych tablic i narzędzia do pracy z tymi tablicami.


+ Oficjalna strona: http://www.numpy.org/
+ Kompletna dokumentacja biblioteki: https://numpy.org/devdocs/reference/index.html
+ Lista funkcji (takich jak: sin, cos, etc):  https://numpy.org/doc/stable/reference/ufuncs.html#ufunc

In [2]:
import numpy as np  # importowanie 

# utworzenie dwówymiarowej tablicy
a = np.array([[1, 3,  2], 
              [1, 99, 2],
              [1, 6,  4]])
a

array([[ 1,  3,  2],
       [ 1, 99,  2],
       [ 1,  6,  4]])

## 2. Tablice ndarray <a name="sec2"></a>

Jeśli  mówimy o danych tablicowwych to dlaczego nie moglibyśmy korzystać z wbudowanego typu zmiennych jakimi są listy. Przecież podstawowa lista daje już jednowymiarową tablicę, a przecież listy można dalej zagnieżdżać tworząc struktury tablic wielowymiarowych np. `moja_lista = [[1, 2], [11, 22], ,[111, 222]]`.

Otóź jest jedna podstawowa zaleta tablic nad listami - wydajność. **Operacje na ndarrays są znacznie szybsze i mniej obciążające dla procesorów aniżeli operacje na listach**. Jest to spowodowane sposobem zapisu danych w pamięci. 
+ W listach **elementy nie muszą być zapisane w pamięci jeden po drugim**. Tak naprawdę lista posiada zapisane referencje (wskaźniki do miejsc w pamięci, gdzie znajdują się realne dane). Przy każdym pobieraniu danych z listy Python robi dwie rzeczy: pobiera wskaźnik, a następnie na jego podstawie pobiera z pamięci wartość. **W listach nie jest wymagane, aby elementy były tego samego typu**, skoro referencja może wskazywać na dowolne miejsce w pamięci, o dowolnym rozmiarze (to akurat jest zaletą list na tablicami ndarray)
+ W  tablicach ndarrays **każdy element jest zapisywany w pamięci jeden po drugim**. W tablicach jest również **wymagany ten sam typ danych w całej tablicy** zapewnia to jednakową ilość pamięci potrzebną na zapisanie każdego elementu, przez co wszystkie bloki są jednakowe. Znając typ danych całej tablicy ndarray system od razu wie, gdzie kończy się jeden, a zaczyna kolejny element. Dzięki tej kontynuacji elementów iterowanie po tablicy jest znacznie wydajniejsze, gdyż nie trzeba szukać w pamięci po wskaźnikach.

**Dużą zaletą ndarrays nad listami jest również możliwość używania funkcji dla wszystkich elementów tablicy (patrz rozdz. 4) oraz przeprowadzania operacji element po elemencie (patrz rozdz. 5).** Mnożenie czy dodawanie dwóch ndarray powoduje wykonanie operacji pomiędzy każdym odpowiadającym elementem tablicy. Niesie to za sobą wymóg zgodności wymiarów tablicy. Występują od niego jednak wyjątki, o których poniżej.


**Wymiary Tablicy Numpy Array**
<img alt="Politechnika Warszawska" style="border-width:0" src="https://1.bp.blogspot.com/-3P-ULcc-aSc/XwINe8CjKgI/AAAAAAAAFFg/LhApCVa2YqUBlnqDDNW4NudSS398L5gjACLcBGAsYHQ/s1600/NumPy%2Barrays.png" />


### 2A. Tworzenie tablicy <a name="sec2A"></a>
**Kompletny spis metod tworzenia tablic** dostępny tutaj: https://numpy.org/devdocs/reference/routines.array-creation.html

#### a) tworzenie jednowymiarowej tablicy

In [2]:
import numpy as np
a = np.array([1,2,3])   
print(type(a), 'a= \n', a.view())
print('size  a = ', np.size(a))   # liczba elementów tablicy
print('shape a = ', np.shape(a))  # wypisanie rozmiarów tablicy 
print('dim a = ', np.ndim(a))  # wypisanie rozmiarów tablicy 

<class 'numpy.ndarray'> a= 
 [1 2 3]
size  a =  3
shape a =  (3,)
dim a =  1


In [5]:
b = np.array([ [1,2,3] ])
print(type(b), 'b= \n', b.view())
print('size  b = ', np.size(b))   # liczba elementów tablicy
print('shape b = ', np.shape(b))  # wypisanie rozmiarów tablicy 
print('dim b = ', np.ndim(b))  # wypisanie rozmiarów tablicy 

<class 'numpy.ndarray'> b= 
 [[1 2 3]]
size  b =  3
shape b =  (1, 3)
dim b =  2


#### b) tworzenie dwuwymiarowej tablicy

In [71]:
c = np.array([[1,2,3], 
              [4,5,6]])
print(c)
print(type(c), 'c= \n', c.view())
print('size  c = ', np.size(c))   # liczba elementów tablicy
print('shape c = ', np.shape(c))  # wypisanie rozmiarów tablicy (wiersze, kolumny)
print('dim c = ', np.ndim(c))  # wypisanie rozmiarów tablicy 

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> c= 
 [[1 2 3]
 [4 5 6]]
size  c =  6
shape c =  (2, 3)


#### d) tworzenie wielowymiarowej tablicy

In [6]:
d = np.array([[(1, 11), (2, 12)], [(3,13), (4,14)]], dtype = float)
print(type(d), 'd= \n', d.view())
print('size  d = ', np.size(d))   # liczba elementów tablicy
print('shape d = ', np.shape(d))  # wypisanie rozmiarów tablicy 
print('dim d = ', np.ndim(d))  # wypisanie rozmiarów tablicy 

<class 'numpy.ndarray'> d= 
 [[[ 1. 11.]
  [ 2. 12.]]

 [[ 3. 13.]
  [ 4. 14.]]]
size  d =  8
shape d =  (2, 2, 2)
dim d =  3


In [ ]:
# 
d = np.array([ 
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],
    [[111, 112, 113],
     [114, 115, 116],
     [117, 118, 119]],], dtype = float)

# print(d.shape())
# print(d.ndim())
print(np.shape(d))
print(np.ndim(d))

print(d[:, 1, 1])

#### e) tworzenie tablic inicjalizacyjnych (placeholder, wypełniacze)

In [73]:
a = np.zeros((3,4))               # utworzenie tablicy zer o wymiarach (3 wiersze, 4 kolumny)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [74]:
b = np.ones((2,3))                # utworzenie tablicy jedynek o wymiarach (2 wiersze, 3 kolumny)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [75]:
c = np.linspace(0, 5, 10)          # utworzenie tablicy: start, stop, ilość wartości
print(c)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [76]:
c = np.arange(0, 5, 1)          # utworzenie tablicy: start, stop, interwał
print(c)

[0 1 2 3 4]


In [77]:
d = np.full((2,2),7)              # utworzenie tablicy o wymiarach (2x2) wypełnionej liczbą 7
print(d)

[[7 7]
 [7 7]]


In [78]:
e = np.eye(2)                     # utworzenie macierzy jednostkowej (2 wiersze, 2 kolumny) - jedynki na diagonalnej
print(e)

[[1. 0.]
 [0. 1.]]


In [79]:
f = np.random.random((2,2))       # utworzenie tablicy z losowymi danymi
print(f)

[[0.13328341 0.36673298]
 [0.78745858 0.24541144]]


In [80]:
g = np.empty((3,2))               # utworzenie pustej tablicy
print(g)

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]]


### 2B. Inspekcja tablic <a name="sec2B"></a>

#### a) sprawdzanie zmiana typów danych

In [81]:
c = np.array([np.arange(4), np.arange(4), np.arange(4)])
b = c.astype('float')           # zapisanie kopii tablicy jako tablicy z innym typem 
print(type(b)) 
print(b.view())

print('b.shape :', b.shape)    # wypisanie rozmiarów tablicy: ZWRACA KTORKE (wiersze, kolumny)
print('b.size  :', b.size)     # liczba elementów tablicy
print('b.ndim  :', a.ndim)     # można też sprawdzić ilość wymiarów tablicy 

<class 'numpy.ndarray'>
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
b.shape : (3, 4)
b.size  : 12
b.ndim  : 2


#### b) sprawdzanie rozmiarów

In [82]:
a = np.arange(2); print(a)      # inicjalizacja tablicy 
print(type(a))                  # wypisanie typu zmiennej tablicy (nie jej elementów) - ndarray 
print(a.dtype)                  # sprawdzenie typu danych tablicy 

a = np.arange(2, dtype='int64') # inicjalizacja tablicy z konkretnym typem danych 
print(a, a.dtype)           

c = np.array([np.arange(4), np.arange(4), np.arange(4)])# inicjalizacja tablicy 
b = c.astype('float')           # zapisanie kopii tablicy jako tablicy z innym typem 
print(type(b)) 
print(b.view())

[0 1]
<class 'numpy.ndarray'>
int64
[0 1] int64
<class 'numpy.ndarray'>
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


###  2C. Typy danych  w tablicy  <a name="sec2C"></a>

In [83]:
np.int32   # 64-bitowe typy liczb całkowitych
np.float64  # zmiennoprzecinkowa z podójna precyzją (double-precision)
np.complex  # liczba zespolona reprezentowana przez 128 zmiennoprzecinkową 
np.bool     # typ logiczny (boolean):  TRUE i FALSE 
np.object   # pythonowy typ obiektu
np.string_  # typ napisowy (string) o stałej długości
np.unicode_ # typ unicode o stałej długości

numpy.str_

### 2D Odnoszenie się do elementów  <a name="sec2D"></a>

#### a) wskazanie elementów

In [84]:
a = np.array([ [1,2,3], [4,5,6], [7, 8, 9] ])
print(a.view())
print('shape :', np.shape(a))
print('wskazany element:', a[1, 2]) # wskazanie elementu

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape : (3, 3)
wskazany element: 6


#### b) wycięcie fragmentu/zakresu tablicy

In [85]:
a = np.array([ [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5] ])
print(a.view())
print('shape :', np.shape(a))
a[0:4, 1:2] # wycięcie fragmentu/zakresu tablicy

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
shape : (3, 5)


array([[2],
       [2],
       [2]])

#### b) wycięcie fragmentu/zakresu tablicy - warunek logiczny

In [1]:
import numpy as np
a = np.array([ [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5] ])
a[a<3]


array([1, 2, 1, 2, 1, 2])

### 2E Fancy indexing  - indeksowanie przy pomocy tablic indeksów<a name="sec2E"></a>

**Fancy indexing**, czyli indeksowanie przy pomocy tablic indeksów, bądź tablic wartości logicznych `True/False`.

Najprostszym sposobem użycia fancy indexing jest przekazanie w nawiasach kwadratowych, w miejscu wybieranego indeksu czy wycinka, całej listy indeksów. W ten sposób w nowopowstałej tablicy zostaną zawarte elementy starej, o indeksach odpowiadających wartością przekazanej tablicy.

In [87]:
a  = np.arange(8)*2
print('tablica a:\n', a )
idx = np.array([2, 5, 0]) # tworzymy tablicę indeksów 
print('tablica indeksów:\n', idx )
a[idx]
print('indeksowania z użycien tablicy indeksów:\n', a[idx])

tablica a:
 [ 0  2  4  6  8 10 12 14]
tablica indeksów:
 [2 5 0]
indeksowania z użycien tablicy indeksów:
 [ 4 10  0]


**Dla przekazanej jako wartość indeksu tablicy wielowymiarowej `idx2`, otrzymamy wynikową tablice wielowymiarową  o kształcie tablicy indeksów `idx`**

In [88]:
a  = np.arange(8)*2
print('tablica a:\n', a )
idx2 = np.array([[0, 7], [1, 3], [4, 1]]) # tworzymy tablicę indeksów 
print('tablica indeksów:\n', idx2 )
print('indeksowania z użycien wielowymiarowe tablicy indeksów:\n', a[idx2])

tablica a:
 [ 0  2  4  6  8 10 12 14]
tablica indeksów:
 [[0 7]
 [1 3]
 [4 1]]
indeksowania z użycien wielowymiarowe tablicy indeksów:
 [[ 0 14]
 [ 2  6]
 [ 8  2]]


Sprawa wygląda trudniej, gdy chcemy w ten sposób indeksować tablicę dwuwymiarową. 

Należy w tym celu utworzyć dwie tablice indeksujące, **obie posiadające dokładnie wymiary oczekiwanej tablicy wynikowej**. Pierwsza z nich odpowiada indeksom głównej osi (przy dwuwymiarowej tablicy - osi wierszy), a druga indeksom osi podrzędnej (kolumny).

Przy indeksowanych tablicach o większej liczbie wymiarów, należy adekwatnie przekazać więcej tablic indeksujących. Odpowiednio jedna na każdy wymiar.

In [89]:
a = np.arange(9).reshape(3,3)
print('tablica a:\n', a )

wiersze = np.array([[0, 2], [1, 1]])
print('tablica wiersze:\n', wiersze )

kolumny = np.array([[0, 1], [2, 0]])
print('tablica kolumny:\n', kolumny )

print('indeksowania :\n', a[wiersze, kolumny])

tablica a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
tablica wiersze:
 [[0 2]
 [1 1]]
tablica kolumny:
 [[0 1]
 [2 0]]
indeksowania :
 [[0 7]
 [5 3]]


Poza tworzeniem niestandardowych wycinków z tablic metoda ta dobrze działa w nadpisywaniu wartości określonych elementów. Wystarczy, przekazując w nawiasach kwadratowych tablicę indeksów przypisać takiemu wyrażeniu jakąś określoną wartość, a otrzymają ją wszystkie wybrane elementy.

In [90]:
a = np.arange(4)
a
a[[1, 2]] = 99
a

array([ 0, 99, 99,  3])

##  3. Kopia vs referencja   <a name="sec3"></a>

Podobnie jak w przypadku list **przypisanie tworzy referencję a nie kopię**. Więc jeśli do zmiennej `B` przypiszemy tylko wycinek tablicy `A` to wykonują zmiany wartości elementów w tablicy `B` b będziemy wprowadzać zmiany w tablicy `A`.

Aby zapobiec takiemu zachowaniu, **dobrą praktyką jest tworzenie kopi tablicy** za pomocą metody **ndarray.copy()**. Tworzy ona tak zwaną głęboką kopię, co oznacza, że tworzony jest nowy obiekt w pamięci, więc referencja obu zmiennych nie wskazuje już na to samo miejsce. Możemy dzięki temu spokojnie wprowadzać zmiany, nie martwiąc się, że zmienimy coś w pierwotnej tablicy.

In [91]:
import numpy as np

# PRZYPISANIE FRAGMENTU TABLICY DO NOWEJ ZMIENNEJ
a  = np.arange(1,10).reshape(3,3) # utworzenie tablicy
print(" ___::: Pierwotnia tablica A :::___  \n", a)

b = a[1:3, 1:3]  # PRZYPISANIE tworzy REFERENCJE (ten sam adres referencyjny w pamięci), a nie kopię
print("B przypisanie: \n", b)

b[0,0] = 999
print('Nowe b po przypisaniu:\n', b)
print('Nowe a:\n', a)


# PRZYPISANIE FRAGMENTU TABLICY DO NOWEJ ZMIENNEJ
c  = np.arange(1,10).reshape(3,3) # utworzenie tablicy
print(" ___::: Pierwotnia tablica C :::___  \n", c)

b = c[1:3, 1:3].copy()  # KOPIA fragmentu tablicy, kopię całej tablicy można również wykonać: b = c[:, :]
print("B przypisanie: \n", b)

b[0,0] = 999
print('Nowe b po kopi:\n', b)
print('Nowe c po kopi:\n', c)

 ___::: Pierwotnia tablica A :::___  
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B przypisanie: 
 [[5 6]
 [8 9]]
Nowe b po przypisaniu:
 [[999   6]
 [  8   9]]
Nowe a:
 [[  1   2   3]
 [  4 999   6]
 [  7   8   9]]
 ___::: Pierwotnia tablica C :::___  
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B przypisanie: 
 [[5 6]
 [8 9]]
Nowe b po kopi:
 [[999   6]
 [  8   9]]
Nowe c po kopi:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## 4. Działanie Numpy - funkcje dla wszystkich elementów tablicy  <a name="sec4"></a>

Biblioteka NumPy udostępnia również użytkownikom **zestaw przygotowanych funkcji, które przyjmują tablicę i zwracają wynik działania przeprowadzony element po elemencie, jako tablicę** o tych samych wymiarach. W skrócie nazywane są unfunc od Universal Functions. Możemy dzięki nim przeprowadzić wiele przydatnych operacji jak liczenie potęg, pierwiastków czy wartości funkcji trygonometrycznych.

Lista funkcji (takich jak: sin, cos, etc):  https://numpy.org/doc/stable/reference/ufuncs.html#ufunc
Większość z funkcji NumPy pozwala również na podanie argumentu który jest wartością skalarną, funkcja zwraca wtedy również wynik obliczeń jako wartość skalarną.

In [92]:
a = np.arange(0.2, 3.14, 0.5)
print(a)

asin = np.sin(a) # użycie funkcji sin dla całej tablicy
print(np.round(asin,2))

bsin = np.sin(3.14)
print(bsin)

[0.2 0.7 1.2 1.7 2.2 2.7]
[0.2  0.64 0.93 0.99 0.81 0.43]
0.0015926529164868282


## 5. Broadcasting - operacje element po elemencie  <a name="sec5"></a>
**Operacje arytmetyczne na tablicach ndarray sa operacjami element po elemencie** (ang. element wise) między dwoma tablicami.

In [93]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 1, 1, 1, 1])
c = a + b
print(c)

[2 3 4 5 6]


Gdy wykonujemy operację arytmetyczną pomiędzy tablicą a wartością skalarną, powyższe reguły są zachowane. Skalar, mimo iż nie jest tablicą ndarray, jest rozumiany jako tablica o wymiarach (1, 1), stąd też niezależnie od wymiarów drugiej tablicy, można go rozciągnąć do jej wymiarów i przeprowadzić operację element po elemencie.

In [94]:
c = np.arange(2,5)
d = c ** 2
e = 4 * c
print(c,'\n',d,'\n',e)

[2 3 4] 
 [ 4  9 16] 
 [ 8 12 16]


**Broadcasting** możemy opisać jako mechanizm wykonywania operacji arytmetycznych **element po elemencie** (ang. element wise** między dwoma tablicami, **w przypadku, gdy tablice nie posiadają tych samych wymiarów**. W bardzo dużym uproszczeniu można to opisać, jako **rozciąganie mniejszej tablicy (kopiowanie kolumn czy wierszy), do momentu, aż wymiary obu tablic będą się zgadzać**. Oczywiście NumPy nie robi żadnego kopiowania, a cały mechanizm dzieje się dzięki iteracją w języku C na zwektoryzowanych tablicach.

In [3]:
import numpy as np
f = np.arange(4)
print('f =', f)
g =  np.ones(3)
print('g =', g)

# dodawanie tablic o różnych wymiarach
h = f + g # < błąd !!  ValueError: operands could not be broadcast together with shapes (4,) (3,) 
print(h)

f = [0 1 2 3]
g = [1. 1. 1.]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

Aby  poprawnie wykonać broadcasting należy odwrócić jedną z tablic, tak aby miała jedną kolumnę i kilka wierszy. 

Na poniższym przykładzie tablica  `f` została odwrócona, teraz główny wymiar (liczba wierszy) `f` wynosi 4, natomiast w g wynosi 1, możemy więc 'rozciągnąć' tablicę a, aby miała 3 jednakowe kolumny. Podobnie rozciągamy' tablicę b aby miała 4 jednakowe wiersze. Teraz już można dodać do siebie tak zdefiniowane tablice.

In [4]:

print('shape f :', np.shape(f))
f.resize(4,1)

print('shape f (po reashape):', np.shape(f))
print(f)
print('shape g:', np.shape(g))
print(g)

h = f + g
print('dodawanie i broadcasting:', h)

shape f : (4,)
shape f (po reashape): (4, 1)
[[0]
 [1]
 [2]
 [3]]
shape g: (3,)
[1. 1. 1.]
dodawanie i broadcasting: [[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


## 6. Operacje logiczne dla tablic  <a name="sec6"></a>

Bardzo przydatną funkcją Numpy jest **wyszukiwanie wartości w tablicy za pomocą funkcji logicznych**

In [ ]:
import random

#utworzenie tablicy
A = np.array([random.randint(0, 20) for i in range(64)])
A = A.reshape(8, 8)
# wyszukiwanie wartości w tablicy za pomocą funkcji logicznych:

B = A == 1 # tablica wartości True/False dla warunku gdzie A == 1
print(B)
B = A > 1 # tablica wartości True/False dla warunku gdzie A > 1
print(B)

NumPy pozwala również **indeksować tablicę za pomocą tablic wartości logicznych**. 
Można to zrealizować za pomocą tablicy logicznej, o tych samych wymiarach co tablica, którą chcemy indeksować.

Pomocne są tutaj broadcasting i proste operacje na tablicach. Gdy wykonamy operację logiczną na całej tablicy (jak poniżej), operacja ta wykona się element po elemencie, a wynikiem będzie właśnie tablica wartości logicznych.

Przekazując tak powstałą tablicę jako indeks innej tablicy, spowodujemy wybranie z niej tylko elementów, dla których w tablicy indeksującej występowało True. Pamiętać trzeba, że nawet jeśli pierwotnie tablica miała więcej niż jeden wymiar, wynik zostanie zwrócony jako tablica jednowymiarowa.


In [96]:
a = np.arange(12).reshape(3, 4)
print('a =\n', a)
b = a % 2 == 0
print('b =\n', b)
c = a[b]
print('c = a[b] =\n', c)

# można tak przypisać określoną, wspólną wartość pewnej grupie elementów, wybranych w operacji logicznej.
a[b] = 99 # wstawi 999 tab gdzie b = True
a[b]

a =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b =
 [[ True False  True False]
 [ True False  True False]
 [ True False  True False]]
c = a[b] =
 [ 0  2  4  6  8 10]


array([99, 99, 99, 99, 99, 99])

**Można tak przypisać określoną, wspólną wartość pewnej grupie elementów, wybranych w operacji logicznej**

In [97]:
c = np.arange(12).reshape(3, 4)
print('a =\n', a)
b = c % 2 == 0
print('b =\n', b)

c[b] = 99 # wstawi 999 tab gdzie b = True
c

a =
 [[99  1 99  3]
 [99  5 99  7]
 [99  9 99 11]]
b =
 [[ True False  True False]
 [ True False  True False]
 [ True False  True False]]


array([[99,  1, 99,  3],
       [99,  5, 99,  7],
       [99,  9, 99, 11]])

## 7. Dane NaN lub None <a name="sec7"></a>
**Jaka jest różnica między NaN, None i np.nan?**

**NaN** to wartość liczbowa zdefiniowana w standardzie zmiennoprzecinkowym IEEE 754. **None** jest wewnętrznym typem Pythona (NoneType) i w tym kontekście bardziej przypomina „nieistniejący” lub „pusty” niż „niepoprawny numerycznie”. 
+ **nan** należy do klasy **float**, natomiast **None** należy do klasy **NoneType**
+ Jeśli wykonasz, powiedzmy, **funkcję liczenia średniej lub sumy na tablicy zawierającej nan, nawet pojedynczej, otrzymasz w rezultacie nan**.
+ **Nie można wykonywać operacji matematycznych, używając None jako argumentu**. Tak więc, w zależności od przypadku, można użyć None jako sposobu, na wskazanie algorytmowi, aby nie uwzględniał nieprawidłowych lub nieistniejących wartości w obliczeniach. Jednak oznaczałoby to, że algorytm powinien przetestować każdą wartość (czy jest None), aby sprawdzić, czy jest to Brak.

In [5]:
5 * np.nan #wynik nan

nan

In [6]:
5 * None #wynikiem jest błąd działania

TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

Numpy ma kilka funkcji, które pozwalają uniknąć wartości NaN, które mogłyby zanieczyścić wyniki, na przykład np.nansumm np.nanstd

**NaN może być używany jako wartość liczbowa w operacjach matematycznych, podczas gdy None nie może (lub przynajmniej nie powinien).**


+ NaN jest używany jako symbol zastępczy (ang. placeholder) dla brakujących danych (NaN ang. _not a number_).Jego podstawową funkcją jest działanie jako symbol zastępczy dla brakujących wartości liczbowych w tablicy.

+ **np.nan -- IEEE 754 jest reprezentacją zmiennoprzecinkową wartości  Not a Number (NaN)**, więcej: 
https://numpy.org/doc/stable/reference/constants.html#numpy.NAN

+ Wartości np.nan nie są sobie równe: `np.nan != np.nan`

+ **NaN i NAN są odpowiednikami definicji nan. Proszę używać nan zamiast NaN.**

In [98]:
a = np.nan
type(a)

float

In [99]:
np.nan == np.nan

False

In [100]:
np.isnan(np.nan)

True

**Utworzenie tablicy nan**

In [101]:
an_array = np.empty((3,3))
an_array[:] = np.NaN
an_array

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

**Obsługa tablic z wartością nan: dodawanie nan**
Dodawanie nan daje w wyniku nan

**None** jest wewnętrznym typem Pythona (NoneType) i w tym kontekście bardziej przypomina „nieistniejący” lub „pusty” niż „niepoprawny numerycznie

In [102]:
a = np.array([3, 23, None, 15, None, 45, 85, None, 5])
np.sum(a) # działanie z None da błąd

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [ ]:
a = np.array([3, 23, np.nan, 15, np.nan, 45, 85, np.nan, 5])
np.sum(a)
print('dodawanie tablicy z nan: ', np.sum(a))
np.nansum(a)
print('dodawanie tablicy z nan: ', np.sum(a))
np.nanmean(a)
print('średnia tablicy z nan: ', np.sum(a))
np.nanstd(a)
print('odchylenie standardowe tablicy z nan: ', np.nanstd(a))

**Obsługa tablic z wartością nan: mnożenie nan**

In [ ]:
a[1] * a[2]

**Wskazanie miejsc z nan**

In [ ]:
boolean_array = np.isnan(a)
print('boolean_array', boolean_array)

index_array = np.argwhere(np.isnan(a))
print('index_array\n', index_array)

## 8. Zapisywanie i wczytywanie tablic  <a name="sec8"></a>
Numpy pozwala przechowywać swoje dane tablicowe (typu array w plikach binarnych) odobnie jak matlab (pliki .mat). Pozwala to szybkie wczytywanie i ponowne działanie na tych tablicach.

In [ ]:
import numpy as np
a= np.full((6,8),7) 
a= np.full((2,2),7) 
np.save('my_array', a)  # zapisze na dysku tablice w formacie binarnym
np.savez('array.npz', a, b) # zapisze na dysku tablice w formacie binarnym
test = np.load('my_array.npy') # odczyta tablice w foracie binarnym numpy
print(test)

## 9. Zapisywanie i wczytywanie plików tekstowych  <a name="sec9"></a>

In [ ]:
import numpy as np
a = np.full((7,6),7) 
a[:,3] = 33 # wstawienie wartosci dla wszystkich wierzy w 4 kolumnie
a[:,4] = 44 # wstawienie wartosci dla wszystkich wierzy w 4 kolumnie
a[:,5] = 55 # wstawienie wartosci dla wszystkich wierzy w 4 kolumnie
b1 = a.astype('int32') 
# zapis: https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.savetxt.html
np.savetxt("myarray.txt", b1, delimiter=',', fmt = '%10.2f', header = 'jakis naglowek')

# odczyt: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.genfromtxt.html
np.genfromtxt("myarray.txt", delimiter=',', skip_header = 1 , usecols =(5, 4, 3, 1) )


## 10. Manipulacje tablicami <a name="sec10"></a>
Kompletny zestaw funkcji dostępny tutaj: https://numpy.org/devdocs/reference/routines.array-manipulation.html

### 10A.  Zmiana kształtu macierzy  - wypłaszczenie<a name="sec10A"></a>

In [ ]:
a = np.array([ [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5] ])
a.ravel() #wypłaszczenie tablicy

Zmiana kształtu macierzy  - zmiana kształtu bez zmiany danych

In [ ]:
import numpy as np
a = np.array([ [1,2,3,4], [1,2,3,4], [1,2,3,4] ])
print('shape a: ', a. shape) #(3x4)
print(a.view())

# Przy zmianie kształtu metodą reshape liczba elementów macierzy wyjścia i wejscia powinna być taka sama!
b = np.reshape(a, (2,6) ) #reshape(a, newshape, order='C')
print('shape b: ', b.shape)
print(b.view())

### Zmiana kształtu macierzy  - zmiana kształtu

In [ ]:
import numpy as np
a = np.array([ [1,2,3,4], [1,2,3,4], [1,2,3,4] ])
print('shape a: ', a. shape) #(3x4)
print(a.view())


b = np.resize(a, (2,3) )#
print('shape b: ', b.shape)
print(b.view())

### 10B. Dodawanie i usuwanie elementów tablicy (append, insert, delete) <a name="sec10B"></a>

#### a) dodawanie elementów do tablicy - append

In [ ]:
import numpy as np

a = np.array([ [1,2,3,4], [1,2,3,4], [1,2,3,4] ])

b = np.append(a, [9,9,9,9])
print(b.view())

#### b) wstawianie elementów do tablicy - insert

In [ ]:
import numpy as np

a = np.array([ [1,2,3,4], [1,2,3,4], [1,2,3,4] ])

b = np.insert(a, 3, 5) # na 3 indeksie wartosc 5
print(b.view())

#### c) usuwanie elementów z tablicy

In [ ]:
import numpy as np

a = np.array([ [1,2,3,4], [1,2,3,4], [1,2,3,4] ])

b = np.delete(a, [3])  # usuwa 5 element
print(b.view())

### 10C. Łączenie tablic (pionowo, poziomo) <a name="sec10C"></a>

In [ ]:
a = np.array([ [1,2,3,4], [1,2,3,4], [1,2,3,4] ])
b = np.array([ [9,9,9,9], [8,8,8,8], [8,8,8,8] ])

np.concatenate((a,b))

#### g) łaczenie tablic pionowo (wertykalnie) i poziomo (horyzontalnie)

In [ ]:
a = np.array([ [1,2,3,4], [1,2,3,4], [1,2,3,4] ])
b = np.array([ [9,9,9,9], [8,8,8,8], [8,8,8,8] ])

v = np.vstack((a,b))
print(v.view())
h = np.hstack((a,b))
print(h.view())

#### h) dzielenie tablic pionowo (wertykalnie) i poziomo (horyzontalnie)

In [ ]:
# Vertykalnie
a = np.array([ [1,2,3,4], 
               [1,2,3,4], 
               [1,2,3,4] ])
b = np.array([ [9,9,9,9], 
               [8,8,8,8], 
               [8,8,8,8] ])
v = np.vstack((a,b))
print(v.view())

vs = np.vsplit(v, 2)
print(vs)


# Horyzontalnie
a = np.array([ [1,2,3,4], 
               [1,2,3,4], 
               [1,2,3,4] ])
b = np.array([ [9,9,9,9], 
               [8,8,8,8], 
               [8,8,8,8] ])
v = np.vstack((a,b))
print(v.view())

hs = np.hsplit(v, 2)
print(hs)